name: ponyc update breakage test

on:
  repository_dispatch:
    types: [shared-docker-linux-builders-updated]

jobs:
  test-libressl-vs-ponyc-latest:
    name: 0.9.0 with ponyc main
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder-with-libressl:latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: make test config=debug ssl=0.9.0

  test-openssl-1_1_1k-vs-ponyc-latest:
    name: 1.1.1k with ponyc main
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder-with-openssl_1.1.1k:latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: make test config=debug ssl=1.1.x
