name: PR

on: pull_request

jobs:
  verify-changelog:
    name: Verify CHANGELOG is valid
    runs-on: ubuntu-latest
    container:
      image: ponylang/changelog-tool:release
    steps:
      - uses: actions/checkout@v1
      - name: Verify CHANGELOG
        run: changelog-tool verify

  test-1_1_x-vs-ponyc-release:
    name: 1.1.x with most recent ponyc release
    runs-on: ubuntu-latest
    container:
      image: ponylang/net-ssl-ci-x86-64-unknown-linux-builder-with-openssl:release
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: make test config=debug ssl=1.1.x

  test-0_9_0-vs-ponyc-release:
    name: 0.9.0 with most recent ponyc release
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder-with-ssl:release
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: make test config=debug ssl=0.9.0
