name: PR

on: pull_request

jobs:
  verify-changelog:
    name: Verify CHANGELOG is valid
    runs-on: ubuntu-latest
    container:
      image: ponylang/changelog-tool:release
    steps:
      - uses: actions/checkout@v1
      - name: Verify CHANGELOG
        run: changelog-tool verify

  test-libressl-vs-ponyc-release:
    name: 0.9.0 with most recent ponyc release
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder-with-libressl:release
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: make test config=debug ssl=0.9.0

  test-openssl-1_1_x-vs-ponyc-release:
    name: 1.1.x with most recent ponyc release
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder-with-openssl_1.1.x:release
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: make test config=debug ssl=1.1.x

  test-windows-vs-ponyc-release:
    name: Windows (LibreSSL) with most recent ponyc release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test with most recent ponyc release
        run: |
          Invoke-WebRequest https://dl.cloudsmith.io/public/ponylang/releases/raw/versions/latest/ponyc-x86-64-pc-windows-msvc.zip -OutFile C:\ponyc.zip;
          Expand-Archive -Path C:\ponyc.zip -DestinationPath C:\ponyc;
          $env:PATH = 'C:\ponyc\bin;' + $env:PATH;
          .\make.ps1 -Command libs 2>&1
          .\make.ps1 -Command test 2>&1
